# Generated by Django 3.2.18 on 2024-10-22 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_alter_time_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
