# Generated by Django 3.2.18 on 2024-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_time_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='turno',
        ),
        migrations.AddField(
            model_name='participante',
            name='time',
            field=models.CharField(default='valor_padrao', max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='modalidade',
            field=models.CharField(choices=[('basquete', 'Basquete'), ('futsal', 'Futsal'), ('handebol', 'Handebol'), ('volei', 'Vôlei')], max_length=50),
        ),
        migrations.AlterField(
            model_name='time',
            name='modalidade',
            field=models.CharField(choices=[('basquete', 'Basquete'), ('futsal', 'Futsal'), ('handebol', 'Handebol'), ('volei', 'Vôlei')], max_length=50),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Time'),
        ),
    ]
